### ISSUE TITLE
Add support for connecting to Azure OpenAI Service

### ISSUE THREAD

**Issue by rhuanbarreto** [Azure/ServiceConnector#2]
I really enjoy using Service Connector! It fixes all my networking configurations in one step!

One feature I wanted to report is to support configuring connections to Azure OpenAI service. Then my container apps can seamlessly connect to it.

**Comment by qianwens** [comment]
@rhuanbarreto thanks for your feedback! We are glad to hear that service connector can help you to set up connection easier. We are working on the Azure OpenAI service support, and it will be released soon.

**Comment by yungezz** [comment]
supported
