### ISSUE TITLE
[Functions] Autodetect language stack in create flow

### ISSUE THREAD

**Issue by ggailey777** [Azure/ServiceConnector#3]
Every function app must have an explicitly defined worker language stack. The worker language is set in the [`FUNCTIONS_WORKER_RUNTIME`](https://learn.microsoft.com/azure/azure-functions/functions-app-settings#functions_worker_runtime) app setting. In the function app UI in the portal, the Service Connection create flow should just read `FUNCTIONS_WORKER_RUNTIME` instead of making customers choose again, or at least auto-propagate the suggested setting. The same should be true for any CLI-based commands. As it is today, the service seems very "bolted-on" for Functions.

**Comment by houk-ms** [comment]
@ggailey777 thanks for the feedback! 

Confirmed that this is a bug on windows type Function, and we will fix it soon.

**Comment by yungezz** [comment]
the fix is deployed. close the issue. Feel free to create new issue if any problem met.
